const order = require('../../models/orderModel')
const cartProduct = require('../../models/cartProduct')
const userModel = require('../../models/userModel')

// Note: orderId is now generated automatically in the model's pre-save hook as sequential numbers

const createOrder = async (req, res) => {
    try {
        const { totalAmount, totalQty, phoneNumber } = req.body
        const userId = req.userId

        console.log("====== CREATE ORDER REQUEST ======")
        console.log("UserId:", userId)
        console.log("Total Amount:", totalAmount)
        console.log("Total Qty:", totalQty)

        if (!userId) {
            return res.status(400).json({
                message: "User ID is required",
                error: true,
                success: false
            })
        }

        // Get cart products
        const cartData = await cartProduct.find({ userId }).populate('productId')
        console.log("Cart items found:", cartData?.length || 0)

        if (!cartData || cartData.length === 0) {
            return res.status(400).json({
                message: "Cart is empty",
                error: true,
                success: false
            })
        }

        // Prepare products array
        const products = cartData.map(item => ({
            productId: item.productId._id,
            quantity: item.quantity,
            price: item.productId.sellingPrice
        }))

        console.log("Products to save:", products.length)

        // Create order (orderId will be auto-generated by model pre-save hook)
        const newOrder = new order({
            userId,
            products,
            totalAmount,
            totalQty,
            phoneNumber,
            orderStatus: 'Confirmed',
            paymentStatus: 'Pending'
        })

        console.log("Order object before save:", JSON.stringify(newOrder, null, 2))
        const savedOrder = await newOrder.save()
        console.log("✅ Order saved successfully with ID:", savedOrder.orderId)
        console.log("====== CREATE ORDER SUCCESS ======")

        // Clear cart after order is placed
        await cartProduct.deleteMany({ userId })
        console.log("Cart cleared for user:", userId)

        res.status(201).json({
            data: savedOrder,
            message: "Order placed successfully",
            success: true
        })
    } catch (err) {
        console.error("❌ CREATE ORDER ERROR:")
        console.error("Error:", err.message)
        console.error("Stack:", err.stack)
        console.log("====== CREATE ORDER ERROR ======")
        
        res.status(400).json({
            message: err.message || "Error creating order",
            error: true,
            success: false
        })
    }
}

const getAllOrders = async (req, res) => {
    try {
        const userId = req.userId
        console.log("UserId:", userId)

        
        const user = await userModel.findById(userId)
        console.log("User role:", user?.role)
        
        if (user.role !== 'ADMIN') {
            return res.status(403).json({
                message: "Admin access required",
                error: true,
                success: false
            })
        }

        const allOrders = await order.find()
            .populate({
                path: 'userId',
                select: 'name email'
            })
            .populate({
                path: 'products.productId',
                select: 'productName sellingPrice'
            })
            .sort({ orderDate: -1 })

        console.log("✅ Found orders:", allOrders.length)
        if (allOrders.length > 0) {
            console.log("First order sample:", JSON.stringify(allOrders[0], null, 2))
            console.log("First order orderId:", allOrders[0].orderId)
        }

        // Assign orderId to orders that don't have one
        let orderCount = 1
        for (let i = 0; i < allOrders.length; i++) {
            if (!allOrders[i].orderId) {
                const letters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
                const letterIndex = Math.floor((orderCount - 1) / 26) % letters.length
                const numberIndex = ((orderCount - 1) % 26) + 1
                const generatedId = letters[letterIndex] + numberIndex
                
                // Update the document
                await order.findByIdAndUpdate(allOrders[i]._id, { orderId: generatedId })
                allOrders[i].orderId = generatedId
                console.log(`✅ Updated order with orderId: ${generatedId}`)
                orderCount++
            } else {
                orderCount++
            }
        }

        res.status(200).json({
            data: allOrders,
            message: "Orders retrieved successfully",
            success: true
        })
    } catch (err) {
        console.error("❌ GET ORDERS ERROR:")
        console.error("Error:", err.message)
        console.log("====== GET ORDERS ERROR ======")
        
        res.status(400).json({
            message: err.message || "Error fetching orders",
            error: true,
            success: false
        })
    }
}

const updateOrderStatus = async (req, res) => {
    try {
        const userId = req.userId
        const { orderId, orderStatus } = req.body

        console.log("====== UPDATE ORDER STATUS REQUEST ======")
        console.log("UserId:", userId)
        console.log("OrderId:", orderId)
        console.log("New Status:", orderStatus)

        // Check if user is admin
        const user = await userModel.findById(userId)
        
        if (user.role !== 'ADMIN') {
            return res.status(403).json({
                message: "Admin access required",
                error: true,
                success: false
            })
        }

        const updatedOrder = await order.findByIdAndUpdate(
            orderId,
            { orderStatus },
            { new: true }
        )

        console.log("✅ Order status updated")
        console.log("====== UPDATE ORDER STATUS SUCCESS ======")

        res.status(200).json({
            data: updatedOrder,
            message: "Order status updated successfully",
            success: true
        })
    } catch (err) {
        console.error("❌ UPDATE ORDER STATUS ERROR:")
        console.error("Error:", err.message)
        console.log("====== UPDATE ORDER STATUS ERROR ======")
        
        res.status(400).json({
            message: err.message || "Error updating order status",
            error: true,
            success: false
        })
    }
}

module.exports = { createOrder, getAllOrders, updateOrderStatus }
